run:
  timeout: 10m

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  funlen:
    lines: 100
    statements: 40
  lll:
    line-length: 200
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G101
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen